name: Todoist Stats

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Todoist Stats
        uses: akashrchandran/todoist-readme@main
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
